version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      # Map the host port (from .env, default 3000) to the container port 3000
      - "${PORT:-3000}:3000"
    env_file:
      - .env
    restart: unless-stopped
    container_name: dockerized-node-starter-app
